from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.auth.entities import Device, RefreshToken, RevokeReason, Session


class DeviceRepository(Protocol):
    async def get_for_user(self, user_id: UUID, device_id: UUID) -> Device | None: ...
    async def get_by_installation(self, user_id: UUID, installation_id: UUID) -> Device | None: ...
    async def list_for_user(self, user_id: UUID) -> list[Device]: ...
    async def add(self, device: Device) -> None: ...
    async def update(self, device: Device) -> None: ...


class SessionRepository(Protocol):
    async def get(self, session_id: UUID) -> Session | None: ...
    async def add(self, session: Session) -> None: ...
    async def list_active_for_user(self, user_id: UUID) -> list[Session]: ...
    async def revoke(self, session_id: UUID, reason: RevokeReason, at: datetime) -> None: ...
    async def revoke_for_device(
        self, user_id: UUID, device_id: UUID, reason: RevokeReason, at: datetime
    ) -> int: ...
    async def revoke_all_for_user(
        self, user_id: UUID, reason: RevokeReason, at: datetime
    ) -> int: ...


class RefreshTokenRepository(Protocol):
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def add(self, token: RefreshToken) -> None: ...
    async def mark_used(self, token_id: UUID, at: datetime) -> bool:
        """Atomar: faqat used_at bo'sh bo'lsa belgilaydi. Poyga holatida False qaytaradi."""
        ...
