from typing import Protocol
from uuid import UUID

from app.domain.reminders.entities import Reminder


class ReminderRepository(Protocol):
    """Barcha metodlar user_id talab qiladi — egalik tekshiruvi repository darajasida."""

    async def add(self, reminder: Reminder) -> None: ...
    async def get_for_user(self, user_id: UUID, reminder_id: UUID) -> Reminder | None: ...
    async def list_for_user(self, user_id: UUID) -> list[Reminder]: ...
    async def update(self, reminder: Reminder) -> None: ...
    async def delete_for_user(self, user_id: UUID, reminder_id: UUID) -> bool: ...
