from datetime import date, datetime
from typing import Protocol
from uuid import UUID

from app.domain.reminders.entities import Reminder


class ReminderRepository(Protocol):
    async def add(self, reminder: Reminder) -> None: ...
    async def get_for_user(self, user_id: UUID, reminder_id: UUID) -> Reminder | None: ...
    async def list_for_user(self, user_id: UUID) -> list[Reminder]: ...
    async def update(self, reminder: Reminder) -> None: ...
    async def soft_delete(self, user_id: UUID, reminder_id: UUID, at: datetime) -> bool: ...
    async def due_between(self, start: date, end: date) -> list[Reminder]:
        """Barcha userlar: yoqilgan va next_due_date [start, end] oralig'ida (scheduler)."""
        ...
    async def overdue(self, before: date) -> list[Reminder]:
        """Barcha userlar: yoqilgan va next_due_date < before (sanani surish uchun)."""
        ...
    async def changed_since(self, user_id: UUID, since: datetime,
                            limit: int) -> list[Reminder]: ...
