from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.accounts.entities import Account


class AccountRepository(Protocol):
    """Barcha metodlar user_id talab qiladi — egalik repository darajasida."""

    async def add(self, account: Account) -> None: ...
    async def get_for_user(self, user_id: UUID, account_id: UUID, *,
                           include_archived: bool = False) -> Account | None: ...
    async def list_for_user(self, user_id: UUID, *,
                            include_archived: bool = False) -> list[Account]: ...
    async def get_default(self, user_id: UUID) -> Account | None: ...
    async def update(self, account: Account) -> None: ...
    async def clear_default(self, user_id: UUID) -> None: ...
    async def delete_for_user(self, user_id: UUID, account_id: UUID) -> bool: ...
    async def changed_since(self, user_id: UUID, since: datetime,
                            limit: int) -> list[Account]: ...
