from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.categories.entities import CategoryPref, UserCategory


class CategoryRepository(Protocol):
    """User kategoriyalari va limitlar. Egalik user_id bilan."""

    async def add(self, category: UserCategory) -> None:
        """Bir user'da bir xil nom (katta-kichik harf farqsiz) — ConflictError."""
        ...
    async def get_for_user(self, user_id: UUID, category_id: UUID) -> UserCategory | None: ...
    async def list_for_user(self, user_id: UUID) -> list[UserCategory]: ...
    async def name_taken(self, user_id: UUID, name: str,
                         exclude_id: UUID | None = None) -> bool: ...
    async def update(self, category: UserCategory) -> None: ...
    async def soft_delete(self, user_id: UUID, category_id: UUID, at: datetime) -> bool: ...
    async def prefs(self, user_id: UUID) -> dict[str, CategoryPref]: ...
    async def save_pref(self, pref: CategoryPref) -> None: ...
    async def changed_since(self, user_id: UUID, since: datetime,
                            limit: int) -> list[UserCategory]: ...
