from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.receipts.entities import Receipt


class ReceiptRepository(Protocol):
    async def add(self, receipt: Receipt) -> None: ...
    async def get_for_user(self, user_id: UUID, receipt_id: UUID) -> Receipt | None: ...
    async def get(self, receipt_id: UUID) -> Receipt | None:
        """Faqat imzolangan URL tekshiruvidan keyin chaqiriladi (imzo egalikni isbotlaydi)."""
        ...
    async def list_for_user(self, user_id: UUID, *, limit: int,
                            after: tuple[datetime, UUID] | None = None) -> list[Receipt]: ...
    async def confirm(self, user_id: UUID, receipt_id: UUID, at: datetime) -> bool: ...
    async def delete_for_user(self, user_id: UUID, receipt_id: UUID) -> bool: ...
    async def unconfirmed_before(self, before: datetime) -> list[Receipt]: ...
    async def delete(self, receipt_id: UUID) -> None: ...
    async def file_keys_for_user(self, user_id: UUID) -> list[str]: ...
