from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.notifications.entities import Notification, PushProvider, PushTarget


class NotificationRepository(Protocol):
    async def add(self, notification: Notification) -> bool:
        """dedupe_key band bo'lsa False (bildirishnoma allaqachon yaratilgan)."""
        ...
    async def list_for_user(self, user_id: UUID, *, limit: int,
                            after: tuple[datetime, UUID] | None = None) -> list[Notification]: ...
    async def unread_count(self, user_id: UUID) -> int: ...
    async def mark_read(self, user_id: UUID, notification_id: UUID, at: datetime) -> bool: ...
    async def mark_all_read(self, user_id: UUID, at: datetime) -> int: ...
    async def clear(self, user_id: UUID, at: datetime) -> int:
        """Soft delete (Clear)."""
        ...
    async def delete(self, user_id: UUID, notification_id: UUID, at: datetime) -> bool:
        """Bittasini soft delete (swipe). Begona yoki yo'q bo'lsa False."""
        ...
    async def pending_push(self, limit: int) -> list[Notification]: ...
    async def set_push_status(self, notification_id: UUID, status: str,
                              attempts: int) -> None: ...


class PushTokenRepository(Protocol):
    """Push token qurilmaga bog'langan (devices jadvali). Egalik user_id bilan tekshiriladi."""

    async def set(self, user_id: UUID, device_id: UUID, provider: PushProvider | None,
                  token: str | None) -> bool: ...
    async def targets(self, user_id: UUID, *, active_only: bool,
                      exclude_device_id: UUID | None = None) -> list[PushTarget]: ...
    async def clear_token(self, token: str) -> None:
        """Provayder token yaroqsiz desa (UNREGISTERED / 410) — o'chiriladi."""
        ...
