from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.goals.entities import Goal, GoalEntry


class GoalRepository(Protocol):
    """Barcha metodlar user_id talab qiladi — egalik tekshiruvi repository darajasida majburiy."""

    async def get_for_user(
        self, user_id: UUID, goal_id: UUID, *, lock: bool = False
    ) -> Goal | None: ...
    async def list_for_user(self, user_id: UUID) -> list[Goal]: ...
    async def add(self, goal: Goal) -> None: ...
    async def update(self, goal: Goal) -> None: ...
    async def soft_delete(self, user_id: UUID, goal_id: UUID, at: datetime) -> bool: ...
    async def saved_amount(self, user_id: UUID, goal_id: UUID) -> int: ...
    async def saved_amounts(self, user_id: UUID) -> dict[UUID, int]: ...
    async def account_backed_amount(self, user_id: UUID, goal_id: UUID) -> int:
        """Hisobga bog'langan yozuvlar bo'yicha saldo (deposit - withdraw)."""
        ...
    async def add_entry(self, entry: GoalEntry) -> bool:
        """dedupe_key band bo'lsa False (auto-save shu oy allaqachon bajarilgan)."""
        ...
    async def list_entries(self, user_id: UUID, goal_id: UUID, *, limit: int,
                           after: tuple[datetime, UUID] | None = None) -> list[GoalEntry]: ...
    async def with_auto_save(self) -> list[Goal]:
        """Barcha userlar bo'yicha (scheduler uchun)."""
        ...
    async def changed_since(self, user_id: UUID, since: datetime, limit: int) -> list[Goal]: ...
