from typing import Protocol
from uuid import UUID

from app.domain.goals.entities import Goal, GoalEntry


class GoalRepository(Protocol):
    """Barcha metodlar user_id talab qiladi — egalik tekshiruvi repository darajasida majburiy."""

    async def get_for_user(self, user_id: UUID, goal_id: UUID, *, lock: bool = False) -> Goal | None: ...
    async def list_for_user(self, user_id: UUID) -> list[Goal]: ...
    async def add(self, goal: Goal) -> None: ...
    async def update(self, goal: Goal) -> None: ...
    async def delete_for_user(self, user_id: UUID, goal_id: UUID) -> bool: ...
    async def saved_amount(self, user_id: UUID, goal_id: UUID) -> int: ...
    async def add_entry(self, entry: GoalEntry) -> None: ...
    async def list_entries(self, user_id: UUID, goal_id: UUID) -> list[GoalEntry]: ...
