from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.exports.entities import Export


class ExportRepository(Protocol):
    async def add(self, export: Export) -> None: ...
    async def get_by_token_hash(self, token_hash: str) -> Export | None: ...
    async def mark_downloaded(self, export_id: UUID, at: datetime) -> bool:
        """Atomar: bir martalik havola. Ikkinchi chaqiruv False qaytaradi."""
        ...
    async def list_expired(self, now: datetime) -> list[Export]: ...
    async def delete(self, export_id: UUID) -> None: ...
    async def file_keys_for_user(self, user_id: UUID) -> list[str]: ...
