from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.exports.entities import Export


class ExportRepository(Protocol):
    async def add(self, export: Export) -> None: ...
    async def get_for_user(self, user_id: UUID, export_id: UUID) -> Export | None: ...
    async def get(self, export_id: UUID) -> Export | None:
        """Imzolangan havola tekshiruvidan keyin (imzo egalikni isbotlaydi)."""
        ...
    async def update(self, export: Export) -> None: ...
    async def mark_downloaded(self, export_id: UUID, at: datetime) -> bool:
        """Atomar: bir martalik havola. Ikkinchi chaqiruv False qaytaradi."""
        ...
    async def pending(self, created_before: datetime) -> list[Export]: ...
    async def list_expired(self, now: datetime) -> list[Export]: ...
    async def delete(self, export_id: UUID) -> None: ...
    async def file_keys_for_user(self, user_id: UUID) -> list[str]: ...
