from typing import Protocol
from uuid import UUID

from app.domain.users.entities import User


class UserRepository(Protocol):
    async def get(self, user_id: UUID) -> User | None: ...
    async def get_by_phone_index(self, phone_index: str) -> User | None: ...
    async def add(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...
    async def set_phone_ciphertext(self, user_id: UUID, ciphertext: bytes) -> None: ...
    async def list_ids(self, *, after: UUID | None, limit: int) -> list[User]:
        """Fon vazifalari uchun userlar bo'yicha sahifalab yurish."""
        ...
    async def purge(self, user_id: UUID) -> None:
        """Userni va unga tegishli barcha shaxsiy ma'lumotni (kaskad) o'chiradi."""
        ...
